# SPDX-License-Identifier: BUSL-1.1
# Copyright 2025-2026 Arsia Labs (Arsia Tecnologia Unipessoal Lda)

"""ARSIA State — state operations, audit records, and breach notifications."""

from arsia_protocol.state.audit import (
    AUDIT_EVENT_TYPES,
    build_audit_record,
    compute_payload_hash,
    derive_event_type_from_intent,
    validate_audit_record,
)
from arsia_protocol.state.breach import (
    BREACH_CAPABILITY,
    PAYLOAD_TYPE_BREACH_NOTIFICATION,
    build_breach_notification,
    validate_breach_notification,
)
from arsia_protocol.state.state import (
    OPERATION_TO_CAPABILITY,
    PAYLOAD_TYPE_DELETE,
    PAYLOAD_TYPE_GET,
    PAYLOAD_TYPE_GRANT,
    PAYLOAD_TYPE_PREFIX,
    PAYLOAD_TYPE_PURGE,
    PAYLOAD_TYPE_QUERY,
    PAYLOAD_TYPE_REVOKE,
    PAYLOAD_TYPE_SET,
    PAYLOAD_TYPE_SNAPSHOT,
    STATE_CAPABILITY_PURGE,
    STATE_CAPABILITY_READ,
    STATE_CAPABILITY_SNAPSHOT,
    STATE_CAPABILITY_WRITE,
    STATE_KEY_MAX_LENGTH,
    STATE_OPERATIONS,
    STATE_RESERVED_KEY_PREFIX,
    STATE_SCOPES,
    STATE_VALUE_MAX_BYTES,
    STATE_WILDCARD_EXCLUDES,
    apply_compliance_defaults_for_state,
    build_conflict_error,
    build_delete_args,
    build_get_args,
    build_grant_args,
    build_grant_result,
    build_purge_args,
    build_purge_result,
    build_query_args,
    build_revoke_args,
    build_revoke_result,
    build_set_args,
    build_snapshot_args,
    compute_effective_retention,
    compute_value_size,
    detect_immutable_field_changes,
    enforce_value_size_limit,
    is_entry_expired,
    is_reserved_key,
    is_within_retention,
    parse_state_key,
    payload_type_for,
    required_capability_for,
    resolve_entry_data_residency,
    resolve_entry_retention,
    validate_custom_state_payload_type,
    validate_eu_ai_act_response,
    validate_state_entry,
    validate_state_key,
    wildcard_covers_state_capability,
)

__all__ = [
    # state.state
    "OPERATION_TO_CAPABILITY",
    "PAYLOAD_TYPE_DELETE",
    "PAYLOAD_TYPE_GET",
    "PAYLOAD_TYPE_GRANT",
    "PAYLOAD_TYPE_PREFIX",
    "PAYLOAD_TYPE_PURGE",
    "PAYLOAD_TYPE_QUERY",
    "PAYLOAD_TYPE_REVOKE",
    "PAYLOAD_TYPE_SET",
    "PAYLOAD_TYPE_SNAPSHOT",
    "STATE_CAPABILITY_PURGE",
    "STATE_CAPABILITY_READ",
    "STATE_CAPABILITY_SNAPSHOT",
    "STATE_CAPABILITY_WRITE",
    "STATE_KEY_MAX_LENGTH",
    "STATE_OPERATIONS",
    "STATE_RESERVED_KEY_PREFIX",
    "STATE_SCOPES",
    "STATE_VALUE_MAX_BYTES",
    "STATE_WILDCARD_EXCLUDES",
    "apply_compliance_defaults_for_state",
    "build_conflict_error",
    "build_delete_args",
    "build_get_args",
    "build_grant_args",
    "build_grant_result",
    "build_purge_args",
    "build_purge_result",
    "build_query_args",
    "build_revoke_args",
    "build_revoke_result",
    "build_set_args",
    "build_snapshot_args",
    "compute_effective_retention",
    "compute_value_size",
    "detect_immutable_field_changes",
    "enforce_value_size_limit",
    "is_entry_expired",
    "is_reserved_key",
    "is_within_retention",
    "parse_state_key",
    "payload_type_for",
    "required_capability_for",
    "resolve_entry_data_residency",
    "resolve_entry_retention",
    "validate_custom_state_payload_type",
    "validate_eu_ai_act_response",
    "validate_state_entry",
    "validate_state_key",
    "wildcard_covers_state_capability",
    # state.audit
    "AUDIT_EVENT_TYPES",
    "build_audit_record",
    "compute_payload_hash",
    "derive_event_type_from_intent",
    "validate_audit_record",
    # state.breach
    "BREACH_CAPABILITY",
    "PAYLOAD_TYPE_BREACH_NOTIFICATION",
    "build_breach_notification",
    "validate_breach_notification",
]
