# SPDX-License-Identifier: BUSL-1.1
# Copyright 2025-2026 Arsia Labs (Arsia Tecnologia Unipessoal Lda)

"""ARSIA Core — message envelope, validation, compliance, errors, encryption, versioning, authorization, and idempotency."""

from __future__ import annotations

from arsia_protocol.core.version import (
    PROTOCOL_VERSION,
    __version__,
    compare_versions,
    extract_content_type_version,
    is_compatible,
    parse_version,
    validate_outbound_version,
)

from arsia_protocol.core.message import (
    ARSIA_CONTENT_TYPE,
    CLOCK_SKEW_TOLERANCE_SECONDS,
    DEFAULT_MAX_MESSAGE_BYTES,
    DEFAULT_REQUEST_TTL_SECONDS,
    AsyncProcessingStatus,
    build_async_status_response,
    check_envelope_size,
    create_approval_decision,
    create_error,
    create_event,
    create_pending_approval,
    create_request,
    create_response,
    format_timestamp,
    is_expired,
    matches_arsia_content_type,
    sign_message,
    verify_message,
)

from arsia_protocol.core.errors import (
    ERROR_REGISTRY,
    RETRY_POLICY,
    ErrorCodeInfo,
    RetryPolicy,
    build_error_envelope,
    build_forbidden_error,
    build_not_implemented_error,
    build_oversight_denied_error,
    build_oversight_expired_error,
    build_payload_too_large_error,
    build_rate_limited_error,
    build_service_unavailable_error,
    compute_retry_delay,
    get_error_info,
    is_retryable,
)

from arsia_protocol.core.encryption import (
    decrypt_and_verify,
    encrypt_payload,
)

from arsia_protocol.core.compliance import (
    ART_6_LEGAL_BASES,
    ART_9_LEGAL_BASES,
    CLASSIFICATION_HIERARCHY,
    ValidationError,
    apply_profile,
    check_oversight_timeout,
    get_clock_skew_seconds,
    get_effective_retention,
    get_profile,
    get_profile_names,
    load_profiles,
    validate_compliance,
    validate_explainability,
)

from arsia_protocol.core.validation import (
    INTENT_CONTENT_FIELD,
    IdentityConsistencyResult,
    PayloadTypeRegistry,
    check_identity_consistency,
    resolve_content_field,
    validate_compliance_field,
    validate_correlation,
    validate_envelope,
    validate_identity_record,
    validate_schema,
    validate_semantic,
)

from arsia_protocol.core.authorization import (
    DEFAULT_CLOCK_SKEW_SECONDS,
    DPOP_TYP,
    JWT_TYP,
    SUPPORTED_ALGORITHMS,
    DPoPValidationResult,
    TokenValidationResult,
    build_dpop_proof,
    build_jwt,
    build_token_request,
    check_scope_coverage,
    compute_jwk_thumbprint,
    decode_jwt,
    parse_scope,
    validate_dpop_proof,
    validate_token_claims,
    verify_dpop_binding,
    verify_jwt_signature,
)

from arsia_protocol.core.idempotency import (
    HEADER_ONLY_RETENTION_HOURS,
    IDEMPOTENCY_KEY_MAX_LENGTH,
    IDEMPOTENCY_KEY_MIN_LENGTH,
    DuplicateIdempotencyKey,
    DuplicateRequestInProgress,
    IdempotencyKeySource,
    IdempotencyRecord,
    IdempotencyScope,
    IdempotencyStatus,
    IdempotencyStore,
    compute_idempotency_expiry,
    extract_envelope_idempotency,
    is_idempotency_record_expired,
    is_valid_idempotency_key,
    resolve_idempotency_key,
    resolve_idempotency_source,
    scope_tuple,
    validate_idempotency_key,
)

__all__ = [
    # version
    "__version__",
    "PROTOCOL_VERSION",
    "compare_versions",
    "extract_content_type_version",
    "is_compatible",
    "parse_version",
    "validate_outbound_version",
    # message
    "ARSIA_CONTENT_TYPE",
    "AsyncProcessingStatus",
    "CLOCK_SKEW_TOLERANCE_SECONDS",
    "DEFAULT_MAX_MESSAGE_BYTES",
    "DEFAULT_REQUEST_TTL_SECONDS",
    "build_async_status_response",
    "check_envelope_size",
    "create_approval_decision",
    "create_error",
    "create_event",
    "create_pending_approval",
    "create_request",
    "create_response",
    "format_timestamp",
    "is_expired",
    "matches_arsia_content_type",
    "sign_message",
    "verify_message",
    # errors
    "ERROR_REGISTRY",
    "ErrorCodeInfo",
    "RETRY_POLICY",
    "RetryPolicy",
    "build_error_envelope",
    "build_forbidden_error",
    "build_not_implemented_error",
    "build_oversight_denied_error",
    "build_oversight_expired_error",
    "build_payload_too_large_error",
    "build_rate_limited_error",
    "build_service_unavailable_error",
    "compute_retry_delay",
    "get_error_info",
    "is_retryable",
    # encryption
    "decrypt_and_verify",
    "encrypt_payload",
    # compliance
    "ART_6_LEGAL_BASES",
    "ART_9_LEGAL_BASES",
    "CLASSIFICATION_HIERARCHY",
    "ValidationError",
    "apply_profile",
    "check_oversight_timeout",
    "get_clock_skew_seconds",
    "get_effective_retention",
    "get_profile",
    "get_profile_names",
    "load_profiles",
    "validate_compliance",
    "validate_explainability",
    # validation
    "INTENT_CONTENT_FIELD",
    "IdentityConsistencyResult",
    "PayloadTypeRegistry",
    "check_identity_consistency",
    "resolve_content_field",
    "validate_compliance_field",
    "validate_correlation",
    "validate_envelope",
    "validate_identity_record",
    "validate_schema",
    "validate_semantic",
    # authorization
    "DEFAULT_CLOCK_SKEW_SECONDS",
    "DPOP_TYP",
    "DPoPValidationResult",
    "JWT_TYP",
    "SUPPORTED_ALGORITHMS",
    "TokenValidationResult",
    "build_dpop_proof",
    "build_jwt",
    "build_token_request",
    "check_scope_coverage",
    "compute_jwk_thumbprint",
    "decode_jwt",
    "parse_scope",
    "validate_dpop_proof",
    "validate_token_claims",
    "verify_dpop_binding",
    "verify_jwt_signature",
    # idempotency
    "DuplicateIdempotencyKey",
    "DuplicateRequestInProgress",
    "HEADER_ONLY_RETENTION_HOURS",
    "IDEMPOTENCY_KEY_MAX_LENGTH",
    "IDEMPOTENCY_KEY_MIN_LENGTH",
    "IdempotencyKeySource",
    "IdempotencyRecord",
    "IdempotencyScope",
    "IdempotencyStatus",
    "IdempotencyStore",
    "compute_idempotency_expiry",
    "extract_envelope_idempotency",
    "is_idempotency_record_expired",
    "is_valid_idempotency_key",
    "resolve_idempotency_key",
    "resolve_idempotency_source",
    "scope_tuple",
    "validate_idempotency_key",
]
